language: cpp
compiler:
  - gcc
  - clang

sudo: false
dist: bionic

addons:
  apt:
    packages:
    - cmake
    - clang
    - libgl1-mesa-glx

before_install:
#  - sudo apt-get update -qq;
  - ${CXX} --version;

script: 
  - echo ${CXX}
  - make sdl2
  - make glfw

