language: cpp
compiler:
  - gcc
#  - clang

sudo: false
dist: bionic

matrix:
  include:
  - os: linux
    compiler: gcc
    script:
    - make sdl2
    - make glfw
#    - cmake . -Bbuild -DCMAKE_BUILD_TYPE=Release
#    - cmake --build build --config Release --target package
  - os: windows
    language: cpp
    install:
    - choco install nsis 7zip
    script:
    - cmake . -Bbuild
    - cmake --build build --config Release --target package
  - os: osx
    osx_image: xcode9.1
    script:
    - echo ${CXX}
    - make sdl2
    - make glfw

addons:
  apt:
    packages:
    - cmake
    - clang
    - libgl1-mesa-dev
    - libx11-dev
    - libxrandr-dev
    - libwayland-dev
    - libxinerama-dev

before_install:
#  - sudo apt-get update -qq;
  - ${CXX} --version;

script:

